# Generated by Django 4.1.5 on 2023-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='master',
            field=models.CharField(default='', max_length=100, verbose_name='Мастер'),
        ),
    ]
