# Generated by Django 4.1.5 on 2023-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя клиента')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('employee', models.CharField(default='', max_length=100, verbose_name='Имя сотрудника')),
                ('equipment', models.CharField(default='', max_length=45, verbose_name='Оборудование')),
                ('breaking', models.CharField(default='', max_length=45, verbose_name='Поломка')),
                ('status', models.CharField(default='', max_length=45, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
                ('note', models.CharField(default='', max_length=250, verbose_name='Примечания')),
            ],
        ),
    ]
